### ISSUE TITLE
issue on vps debian

### ISSUE THREAD

**Issue by FlipfudgeV2** [VissarionSB/Vissarion#3]
Traceback (most recent call last):
  File "/root/Vissarion/main.py", line 9, in <module>
    from src.modules.sessions_manager import sessions_manager
ModuleNotFoundError: No module named 'src.modules.sessions_manager'

**Comment by archivine** [comment]
Just pushed a fix.
The error threw up, because I renamed the session manager class and forgot to change the imports.
Should be good now.
