### ISSUE TITLE
SyntaxError: Invalid syntax

### ISSUE THREAD

**Issue by Packjackisback** [VissarionSB/Vissarion#6]
Quite possibly a version issue, but it immediately (Less than half a second) throws the error `File "/home/user/main.py", line 45
    match (config.read()["startup_state"]["activity"]):
                                                       ^
SyntaxError: invalid syntax`
Running python 3.9.3 on linux armhf.

**Comment by archivine** [comment]
Run it on python 3.10+

**Comment by Packjackisback** [comment]
Thanks <3
