### ISSUE TITLE
ERROR ON LINUX VPS

### ISSUE THREAD

**Issue by FlipfudgeV2** [VissarionSB/Vissarion#7]
File "/root/Vissarion/main.py", line 18, in <module>
    bot = commands.Bot(command_prefix=config.read()['commands']['prefix'], self_bot=True, caseinsensitive=True)
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by archivine** [comment]
Use the discord.py-self fork.
https://github.com/dolfies/discord.py-self
