### ISSUE TITLE
Botbase issue

### ISSUE THREAD

**Issue by Packjackisback** [VissarionSB/Vissarion#8]
I'm running python3.10, and install the requirements via `pip3.10 install -r requirements.txt`, and then `python3.10 main.py` to run it. 

It returns `python3.10 main.py
Traceback (most recent call last):
  File "/home/kali/haxor/dis/Vissarion/main.py", line 7, in <module>
    from src.session import client
  File "/home/kali/haxor/dis/Vissarion/src/session.py", line 2, in <module>
    import discord_rpc, time, requests, random
ModuleNotFoundError: No module named 'discord_rpc'`

I try again, installing discord_rpc by itself, with `pip3.10 install discord_rpc`, but nothing different comes from it.

When I run `pip3.10 list` it shows discord-rpc as being installed, so I am going to modify it to import that.

**Comment by Packjackisback** [comment]
Specifically 3.10.6, and I fixed it by appending .py to the module name, so 
`pip3.10 install discord_rpc.py`, and fixing another similar problem with ua_parser, but I run into a different error that seems to (somehow) be a version error.

**Comment by Packjackisback** [comment]
`Traceback (most recent call last):
  File "/home/kali/haxor/dis/Vissarion/main.py", line 18, in <module>
    bot = commands.Bot(command_prefix=config.read()['commands']['prefix'], self_bot=True, caseinsensitive=True)
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'`

**Comment by Packjackisback** [comment]
I'm wondering if botbase is the wrong version on my system.

**Comment by archivine** [comment]
Use discord.py-self, not discord.py

**Comment by Packjackisback** [comment]
I'll try that. You mean installing it with pip, right?

**Comment by archivine** [comment]
yeah

**Comment by archivine** [comment]
closed for inactivity
